apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: petclinic
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: petclinicroot
  MYSQL_DATABASE: petclinic
  MYSQL_USER: petclinic
  MYSQL_PASSWORD: petclinicpass
