apiVersion: v1
kind: ConfigMap
metadata:
  name: petclinic-configmap
  namespace: petclinic
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SPRING_CLOUD_CONFIG_URI: "http://config-server:8888"
  SPRING_CONFIG_IMPORT: "optional:configserver:http://config-server:8888"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql:3306/petclinic"
  SPRING_CLOUD_CONFIG_FAIL_FAST: "true"
